apply plugin: 'com.android.application'

android {
    namespace 'com.example.sunwidget'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.sunwidget"
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName "1.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
